---
# file: roles/docker/tasks/main.yml

- name: Install docker
  apt:
    deb: https://downloads.hypriot.com/docker-hypriot_1.10.3-1_armhf.deb
    state: present

- user:
    name: pi
    groups: docker 
    append: yes

- name: Enable docker to be started on bootup
  systemd:
    name: docker.service
    enabled: yes
